config/routes.rb
Rails.application.routes.draw do
  root 'houses#index'
  resources   :houses, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/energy_usage.rb
class EnergyUsage < ApplicationRecord
  belongs_to  :house

  validates   :label,             presence: true
  validates   :house_id,          presence: true
  validates   :year,              presence: true
  validates   :month,             presence: true
  validates   :temperature,       presence: true
  validates   :daylight,          presence: true
  validates   :energyproduction,  presence: true
end

app/models/house.rb
class House < ApplicationRecord
  has_many  :energy_usages, dependent: :destroy

  validates :firstname,     presence: true
  validates :lastname,      presence: true
  validates :city,          presence: true, inclusion: { in: %w(London Cambridge Oxford) }
  validates :num_of_people, presence: true
  validates :has_child,     inclusion: { in: [true, false] }

  def has_child?
    has_child ? 'Yes' : 'No'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
    @show_energies = @house.energy_usages.order(:house_id, :label)
    @all_energies = EnergyUsage.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
  def avg_energy_production(show_energies, all_energies)
    avg = []
    i = 0
    show_energies.length.times do
      array = all_energies.map{|t| t.energyproduction if t.label == i }.compact
      avg << array.sum / array.length
      i += 1
    end
    return avg
  end
end

app/views/houses/index.html.erb
<div class="container my-5">
  <h1>House Energy Usage</h1>
  <p>Click 'show' to see charts</p>
  <div class="my-5">
    <table class="table table-sm table-bordered text-center table-hover">
      <thead class="thead-light">
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>City</th>
          <th>num_of_people</th>
          <th>has_child</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @houses.each do |house| %>
          <tr>
            <td><%= house.firstname %></td>
            <td><%= house.lastname %></td>
            <td><%= house.city %></td>
            <td><%= house.num_of_people %></td>
            <td><%= house.has_child? %></td>
            <td><%= link_to 'Show', house %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/houses/show.html.erb
<div class="container">
  <div class="w-50 mt-5 mx-auto">
    <table class="table table-sm">
      <tbody>
        <tr>
          <th>Firstname</th>
          <td><%= @house.firstname %></td>
        </tr>
        <tr>
          <th>Lastname</th>
          <td><%= @house.lastname %></td>
        </tr>
        <tr>
          <th>City</th>
          <td><%= @house.city %></td>
        </tr>
        <tr>
          <th>Num of people</th>
          <td><%= @house.num_of_people %></td>
        </tr>
        <tr>
          <th>Has child</th>
          <td><%= @house.has_child? %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="w-100 my-5">
    <canvas id="myChart1">
      Canvas not supported...
    </canvas>
  </div>

  <div class="w-100 mb-5">
    <canvas id="myChart2"></canvas>
  </div>

  <div class="text-center my-5">
    <button type="button" class="btn btn-outline-primary px-3 mr-5" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      View detailed information
    </button>
    <%= link_to 'Back', houses_path, class: 'btn btn-outline-secondary px-3 ml-5' %>
  </div>

  <div class="collapse" id="collapseExample">
    <table class="my-5 table table-sm table-bordered text-center">
      <thead class="thead-light">
        <tr>
          <th>Year</th>
          <th>Month</th>
          <th>Temperature</th>
          <th>Daylight</th>
          <th>Energy production</th>
        </tr>
      </thead>

      <tbody>
        <% @show_energies.each do |energy| %>
          <tr>
            <td><%= energy.year %></td>
            <td><%= energy.month %></td>
            <td><%= energy.temperature %></td>
            <td><%= energy.daylight %></td>
            <td><%= energy.energyproduction %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script>
  (function() {
    'use strict';

    var type = 'line';
    var data = {
      labels: <%= @show_energies.pluck(:year, :month) %>,
      datasets: [{
        label: 'You',
        data: <%= @show_energies.pluck(:energyproduction) %>,
        borderColor: 'blue',
        backgroundColor: 'rgba(0, 0, 255, 0.1)'
      }, {
        label: 'Average',
        data: <%= avg_energy_production(@show_energies, @all_energies) %>,
        borderColor: 'orange',
        fill: false,
      }]
    };
    var options = {
      scales: {
        yAxes: [{
          ticks: {
            suggestedMin: 0,
            stepSize: 100,
          }
        }]
      },
      title: {
        display: true,
        text: 'Energy Production',
        fontSize: 30,
      },
      animation: {
        duration: 0
      },
    }
    var ctx = document.getElementById('myChart1').getContext('2d');
    var myChart = new Chart(ctx, {
      type: type,
      data: data,
      options: options
    });
  })();

  (function() {
    'use strict';

    var type = 'bar';
    var data = {
      labels: <%= @show_energies.pluck(:year, :month) %>,
      datasets: [{
        label: 'Temperature',
        data: <%= @show_energies.pluck(:temperature) %>,
        borderColor: 'red',
        backgroundColor: 'rgba(255, 0, 0, 0.6)'
      }, {
        label: 'Daylight',
        data: <%= @show_energies.pluck(:daylight) %>,
        borderColor: 'green',
        backgroundColor: 'rgba(0, 255, 0, 0.6)'
      }, {
        label: 'Energy Production',
        data: <%= @show_energies.pluck(:energyproduction) %>,
        borderColor: 'blue',
        backgroundColor: 'rgba(0, 0, 255, 0.6)'
      }]
    };
    var options = {
      scales: {
        yAxes: [{
          ticks: {
            suggestedMin: 0,
            stepSize: 100,
          }
        }]
      },
      title: {
        display: true,
        text: 'Temperature / Daylight / Energy Production',
        fontSize: 30,
      },
      animation: {
        duration: 0
      },
    }
    var ctx = document.getElementById('myChart2').getContext('2d');
    var myChart = new Chart(ctx, {
      type: type,
      data: data,
      options: options
    });
  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShogoHarada</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>